### ISSUE TITLE
TravisCI error raise ReadTimeoutError(self._pool, None, 'Read timed out.')

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#213]
[`Python 3.5; PYSAL_PYPI=true, PYSAL_PLUS=false`] TravisCI error ([#1080.3](https://travis-ci.org/pysal/spaghetti/jobs/467619634)) when attempting to collect [`libpysal`](https://github.com/pysal/libpysal).

```
3.5 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.5.tar.bz2
$ curl -sSf -o python-3.5.tar.bz2 ${archive_url}
$ sudo tar xjf python-3.5.tar.bz2 --directory /
git.checkout
1.26s$ git clone --depth=50 --branch=master https://github.com/pysal/spaghetti.git pysal/spaghetti
Cloning into 'pysal/spaghetti'...
remote: Enumerating objects: 1857, done.
remote: Counting objects: 100% (1857/1857), done.
remote: Compressing objects: 100% (656/656), done.
remote: Total 1857 (delta 1235), reused 1764 (delta 1164), pack-reused 0
Receiving objects: 100% (1857/1857), 4.86 MiB | 15.17 MiB/s, done.
Resolving deltas: 100% (1235/1235), done.
$ cd pysal/spaghetti
$ git checkout -qf fde9ee59d286dc3d36ffbbff09bc64fdba4ab455
Setting environment variables from .travis.yml
$ export PYSAL_PYPI=true
$ export PYSAL_PLUS=false
0.00s$ source ~/virtualenv/python3.5/bin/activate
$ python --version
Python 3.5.6
$ pip --version
pip 18.0 from /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pip (python 3.5)
before_install.1
0.51s$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
--2018-12-13 17:29:53--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.18.10, 104.16.19.10, 2606:4700::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62574861 (60M) [application/x-sh]
Saving to: ‘miniconda.sh’
100%[======================================>] 62,574,861   141MB/s   in 0.4s   
2018-12-13 17:29:53 (141 MB/s) - ‘miniconda.sh’ saved [62574861/62574861]
before_install.2
0.00s$ chmod +x miniconda.sh
before_install.3
11.35s$ ./miniconda.sh -b -p ./miniconda
PREFIX=/home/travis/build/pysal/spaghetti/miniconda
installing: python-3.7.0-hc3d631a_0 ...
Python 3.7.0
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libgcc-ng-8.2.0-hdf63c60_1 ...
installing: libstdcxx-ng-8.2.0-hdf63c60_1 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2p-h14c3975_0 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-h7b6447c_5 ...
installing: tk-8.6.8-hbc83047_0 ...
installing: sqlite-3.24.0-h84994c4_0 ...
installing: asn1crypto-0.24.0-py37_0 ...
installing: certifi-2018.8.24-py37_1 ...
installing: chardet-3.0.4-py37_1 ...
installing: idna-2.7-py37_0 ...
installing: pycosat-0.6.3-py37h14c3975_0 ...
installing: pycparser-2.18-py37_1 ...
installing: pysocks-1.6.8-py37_0 ...
installing: ruamel_yaml-0.15.46-py37h14c3975_0 ...
installing: six-1.11.0-py37_1 ...
installing: cffi-1.11.5-py37he75722e_1 ...
installing: setuptools-40.2.0-py37_0 ...
installing: cryptography-2.3.1-py37hc365091_0 ...
installing: wheel-0.31.1-py37_0 ...
installing: pip-10.0.1-py37_0 ...
installing: pyopenssl-18.0.0-py37_0 ...
installing: urllib3-1.23-py37_0 ...
installing: requests-2.19.1-py37_0 ...
installing: conda-4.5.11-py37_0 ...
installation finished.
before_install.4
0.00s$ export PATH=`pwd`/miniconda/bin:$PATH
before_install.5
20.35s$ conda update --yes conda
Solving environment: done
## Package Plan ##
  environment location: /home/travis/build/pysal/spaghetti/miniconda
  added / updated specs: 
    - conda
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    python-3.7.1               |       h0371630_3        36.4 MB
    sqlite-3.25.3              |       h7b6447c_0         1.9 MB
    cryptography-2.4.1         |   py37h1ba5d50_0         607 KB
    certifi-2018.11.29         |           py37_0         146 KB
    openssl-1.1.1a             |       h7b6447c_0         5.0 MB
    ------------------------------------------------------------
                                           Total:        44.0 MB
The following packages will be UPDATED:
    certifi:      2018.8.24-py37_1     --> 2018.11.29-py37_0   
    cryptography: 2.3.1-py37hc365091_0 --> 2.4.1-py37h1ba5d50_0
    openssl:      1.0.2p-h14c3975_0    --> 1.1.1a-h7b6447c_0   
    python:       3.7.0-hc3d631a_0     --> 3.7.1-h0371630_3    
    sqlite:       3.24.0-h84994c4_0    --> 3.25.3-h7b6447c_0   
Downloading and Extracting Packages
python-3.7.1         | 36.4 MB   | ##################################### | 100% 
sqlite-3.25.3        | 1.9 MB    | ##################################### | 100% 
cryptography-2.4.1   | 607 KB    | ##################################### | 100% 
certifi-2018.11.29   | 146 KB    | ##################################### | 100% 
openssl-1.1.1a       | 5.0 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
before_install.6
0.16s$ conda config --append channels conda-forge
before_install.7
21.89s$ conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
Solving environment: ...working... done
## Package Plan ##
  environment location: /home/travis/build/pysal/spaghetti/miniconda/envs/test-env
  added / updated specs: 
    - python=3.5
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    pip-10.0.1                 |           py35_0         1.8 MB
    setuptools-40.2.0          |           py35_0         571 KB
    certifi-2018.8.24          |           py35_1         139 KB
    python-3.5.6               |       hc3d631a_0        28.3 MB
    zlib-1.2.11                |       h7b6447c_3         120 KB
    wheel-0.31.1               |           py35_0          63 KB
    ncurses-6.1                |       he6710b0_1         958 KB
    ------------------------------------------------------------
                                           Total:        31.9 MB
The following NEW packages will be INSTALLED:
    ca-certificates: 2018.03.07-0           
    certifi:         2018.8.24-py35_1       
    libedit:         3.1.20170329-h6b74fdf_2
    libffi:          3.2.1-hd88cf55_4       
    libgcc-ng:       8.2.0-hdf63c60_1       
    libstdcxx-ng:    8.2.0-hdf63c60_1       
    ncurses:         6.1-he6710b0_1         
    openssl:         1.0.2p-h14c3975_0      
    pip:             10.0.1-py35_0          
    python:          3.5.6-hc3d631a_0       
    readline:        7.0-h7b6447c_5         
    setuptools:      40.2.0-py35_0          
    sqlite:          3.25.3-h7b6447c_0      
    tk:              8.6.8-hbc83047_0       
    wheel:           0.31.1-py35_0          
    xz:              5.2.4-h14c3975_4       
    zlib:            1.2.11-h7b6447c_3      
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
before_install.8
0.12s$ source activate test-env
install.1
4.56s$ conda install --yes pip
Solving environment: done
# All requested packages already installed.
83.87s$ if "$PYSAL_PYPI"; then echo 'testing pypi libpysal' && pip install libpysal; else echo 'testing git libpysal'; git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../; fi;
testing pypi libpysal
Collecting libpysal
  Downloading https://files.pythonhosted.org/packages/c5/6b/6107c51b172a7032bc7e85acd35638af2b9b66dec6d3df042664792d3fde/libpysal-4.0.1.tar.gz (24.4MB)
    70% |██████████████████████▌         | 17.2MB 645kB/s eta 0:00:12Exception:
Traceback (most recent call last):
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 674, in unpack_http_url
    progress_bar)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 586, in written_chunks
    for chunk in chunks:
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_internal/download.py", line 575, in resp_read
    decode_content=False):
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')

pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

The command "if "$PYSAL_PYPI"; then echo 'testing pypi libpysal' && pip install libpysal; else echo 'testing git libpysal'; git clone https://github.com/pysal/libpysal.git; cd libpysal; pip install .; cd ../; fi;" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by jGaboardi** [comment]
self resolved
