### ISSUE TITLE
pandas.core error leading to Travis CI failure

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#240]
`AttributeError: module 'pandas' has no attribute 'core'`

```
======================================================================
ERROR: Failure: AttributeError (module 'pandas' has no attribute 'core')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/pysal/spaghetti/spaghetti/__init__.py", line 7, in <module>
    from .network import Network, PointPattern, SimulatedPointPattern
  File "/home/travis/build/pysal/spaghetti/spaghetti/network.py", line 7, in <module>
    from . import util
  File "/home/travis/build/pysal/spaghetti/spaghetti/util.py", line 3, in <module>
    from libpysal import cg
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/__init__.py", line 28, in <module>
    from . import io
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/io/__init__.py", line 3, in <module>
    from .iohandlers import *
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/io/iohandlers/__init__.py", line 4, in <module>
    from . import gwt
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/io/iohandlers/gwt.py", line 3, in <module>
    from ...weights.weights import W
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/weights/__init__.py", line 2, in <module>
    from .distance import *
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/weights/distance.py", line 7, in <module>
    from .util import isKDTree, get_ids, get_points_array_from_shapefile,\
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/libpysal/weights/util.py", line 17, in <module>
    import geopandas as gpd
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/geopandas/geoseries.py", line 5, in <module>
    from pandas import Series
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/core/frame.py", line 66, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/travis/build/pysal/spaghetti/miniconda/envs/test-env/lib/python3.5/site-packages/pandas/core/generic.py", line 40, in <module>
    import pandas.core.indexing as indexing
AttributeError: module 'pandas' has no attribute 'core'
```

**Comment by jGaboardi** [comment]
Resolved in #248
