### ISSUE TITLE
docs failing with rtree

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#268]
Following the introduction of `rtree` as a dependency in #259, [doc builds are failing](https://readthedocs.org/projects/pysal-spaghetti/builds/9054292/). May be the same issue as gboeing/osmnx#45 and mikedh/trimesh#189. Will try adding `rtree` as a dependency that must be installed via `conda-forge`.

@sjsrey 

```
Running Sphinx v2.0.1
/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/libpysal/weights/util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/checkouts/latest/doc/conf.py", line 26, in <module>
    import spaghetti
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/__init__.py", line 7, in <module>
    from .network import Network, PointPattern, SimulatedPointPattern
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/network.py", line 7, in <module>
    from . import util
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/util.py", line 5, in <module>
    from rtree import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 196, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 371, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/checkouts/latest/doc/conf.py", line 26, in <module>
    import spaghetti
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/__init__.py", line 7, in <module>
    from .network import Network, PointPattern, SimulatedPointPattern
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/network.py", line 7, in <module>
    from . import util
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/util.py", line 5, in <module>
    from rtree import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/checkouts/latest/doc/conf.py", line 26, in <module>
    import spaghetti
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/__init__.py", line 7, in <module>
    from .network import Network, PointPattern, SimulatedPointPattern
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/network.py", line 7, in <module>
    from . import util
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/spaghetti/util.py", line 5, in <module>
    from rtree import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```

**Comment by jGaboardi** [comment]
It appears [`rtree` is already being installed via `conda-forge`](https://github.com/pysal/spaghetti/blob/59f3bd49c7b5d4d65ce6b05ab18224d936651f42/.travis.yml#L51)...

**Comment by jGaboardi** [comment]
How to force [`readthedocs` to install via `conda-forge`](https://readthedocs.org/projects/pysal-spaghetti/builds/9054355/)...? 

```bash
$ /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/.cache/pip -r requirements.txt
```
```
Collecting scipy>=0.11 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f0/30/526bee2ce18c066f9ff13ba89603f6c2b96c9fd406b57a21a7ba14bf5679/scipy-1.2.1-cp35-cp35m-manylinux1_x86_64.whl (24.7MB)
Collecting numpy>=1.3 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f6/f3/cc6c6745347c1e997cc3e58390584a250b8e22b6dfc45414a7d69a3df016/numpy-1.16.3-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
Collecting pandas (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/74/24/0cdbf8907e1e3bc5a8da03345c23cbed7044330bb8f73bb12e711a640a00/pandas-0.24.2-cp35-cp35m-manylinux1_x86_64.whl (10.0MB)
Collecting esda (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/3e/84/bff39fdd34fc7f2dd3e0a1b7a6b92cea8ca17ce0ab9359a96ed301947cd6/esda-2.0.0.tar.gz (46kB)
Collecting rtree (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/33/0d/0bcb0fdd759570e85697189f675fa462131e5636482f2832288bbe4bb6f7/Rtree-0.8.3-py3-none-any.whl
Collecting python-dateutil>=2.5.0 (from pandas->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Requirement already satisfied: pytz>=2011k in /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages (from pandas->-r requirements.txt (line 3)) (2019.1)
Collecting libpysal (from esda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/c5/6b/6107c51b172a7032bc7e85acd35638af2b9b66dec6d3df042664792d3fde/libpysal-4.0.1.tar.gz (24.4MB)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages (from rtree->-r requirements.txt (line 5)) (40.9.0)
Requirement already satisfied: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/envs/latest/lib/python3.5/site-packages (from python-dateutil>=2.5.0->pandas->-r requirements.txt (line 3)) (1.12.0)
Building wheels for collected packages: esda, libpysal
  Building wheel for esda (setup.py): started
  Building wheel for esda (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/.cache/pip/wheels/bf/8b/0c/d4323688d80d66b94f30cd6373a640b9a8e55cdd9e69f8b453
  Building wheel for libpysal (setup.py): started
  Building wheel for libpysal (setup.py): finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pysal-spaghetti/.cache/pip/wheels/b9/7a/55/777eb685de870d4633c21d7ffe537ecc5ad4eede1bb3d0468e
Successfully built esda libpysal
Installing collected packages: numpy, scipy, python-dateutil, pandas, libpysal, esda, rtree
Successfully installed esda-2.0.0 libpysal-4.0.1 numpy-1.16.3 pandas-0.24.2 python-dateutil-2.8.0 rtree-0.8.3 scipy-1.2.1
```

**Comment by jGaboardi** [comment]
The update of `readthedocs.yml` proposed in pysal/giddy#92 did not solve the particular issue currently causing the `spaghetti` docs to fail.

**Comment by jGaboardi** [comment]
@weikang9009 Can you take a look at this if you have a chance?

**Comment by weikang9009** [comment]
@jGaboardi Of course. Am looking at it!

**Comment by jGaboardi** [comment]
related to #294
