### ISSUE TITLE
tarball jobs failing on Travis

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#343]
Currently the [`tarball ` jobs](https://github.com/pysal/spaghetti/blob/d4930d62c9073791b9f08dac6f4ee698808050e2/.travis.yml#L79-L82) are [failing on travis](https://travis-ci.org/pysal/spaghetti/jobs/628546231#L782-L795), seemingly due to an issue with version `twine`/[`importlib`](https://docs.python.org/3/library/importlib.metadata.html):

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/twine/__init__.py", line 22, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/bin/twine", line 6, in <module>
    from twine.__main__ import main
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/twine/__init__.py", line 24, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
The command "if [[ $TRAVIS_JOB_NAME == tarball* ]]; then pip wheel . -w dist --no-deps; twine check dist/*; fi" exited with 1.
```

**Comment by jGaboardi** [comment]
This appears to have been [remedied](https://travis-ci.org/pysal/spaghetti/jobs/629115880?utm_medium=notification&utm_source=github_status).

**Comment by jGaboardi** [comment]
#382

**Comment by jGaboardi** [comment]
Another cryptic `tarball` failure in [build #2161.5](https://travis-ci.org/pysal/spaghetti/jobs/640107882?utm_medium=notification&utm_source=github_status)
```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/TEST/bin/twine", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/twine/__main__.py", line 25, in main
    return dispatch(sys.argv[1:])
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/twine/cli.py", line 72, in dispatch
    main = registered_commands[args.command].load()
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    self.require(*args, **kwargs)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2466, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zipp 0.0.0 (/home/travis/miniconda/envs/TEST/lib/python3.7/site-packages), Requirement.parse('zipp>=0.5'), {'importlib-metadata'})
The command "if [[ $TRAVIS_JOB_NAME == tarball* ]]; then pip wheel . -w dist --no-deps; twine check dist/*; fi" exited with 1
```
